# Generated by Django 3.1.7 on 2021-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
